### ISSUE TITLE
Game crashes with an IllegalAccessError upon trying to pour a bucket of molten diamond + Optimizations

### ISSUE THREAD

**Issue by Nexonus** [Mysticpasta1/Volcanic-Overhaul#1]
Hi, I've been really interested in your project! ^^ 

I've been testing it today to check out how it performs, but I've had a huge difficulty running it on my computer. At first I used a 2GB memory allocation but the world was unable to generate due to amount of features and depth, 3GB worked a bit better but do you think it'd be possible to optimize world generation? - At this very point I'm only able to run this single mod with this much memory.

Another issue I've encountered was a crash which occured when I tried to pour a bucket of molten diamond. The game crashed instantly with an IllegalAccessError.:
https://pastebin.com/TsaCNYQa

I've also seen some of the upper Mantle blocks emitting a bit of 'black light' / shadow around themselves opposite to the lower mantle blocks which are emissive. Is this intentional? 

Thanks for the insight! :)

**Comment by Mysticpasta1** [comment]
the project due to the depth should take 4GB of memory any less is a miracle

**Comment by Mysticpasta1** [comment]
the illegal access error should be fixed in the next version and as for the block light thing the upper mantle block have a emission of light that is around 1 - 6 so it may be the case that some is wrong with minecraft and that
